server:
  port: 9091
  errot:
    include-message: always
    inclue-binding-errors: always

feign.client.config.default:
  loggerLevel: full
  connectTimeout: 5000

logging.level:
  br.com.tt.petshop.cliente: DEBUG

  client.credito.url: https://imersao-credito-api.herokuapp.com

